perlanguages:
  - en
  - es
  - zh-cn
  - zh-tw
  - ar
  - fr
  - de
  - pt-br
  - tr
  - ja
  - ko

default_lang: en

en:
  url: "https://markleighedu.github.io"
  baseurl: "/"
  title: "Mark Leigh Educator Blog"

es:
  url: "https://markleighedu.github.io"
  baseurl: "/es"
  title: "Blog del Educador Mark Leigh"

zh-cn:
  url: "https://markleighedu.github.io"
  baseurl: "/zh-cn"
  title: "Mark Leigh 马克.李教育博客"

zh-tw:
  url: "https://markleighedu.github.io"
  baseurl: "/zh-tw"
  title: "Mark Leigh 馬克.李教育博客"

ar:
  url: "https://markleighedu.github.io"
  baseurl: "/ar"
  title: "مدونة مارك لي للمعلم"

fr:
  url: "https://markleighedu.github.io"
  baseurl: "/fr"
  title: "Blog de Mark Leigh pour les éducateurs"

de:
  url: "https://markleighedu.github.io"
  baseurl: "/de"
  title: "Mark Leigh Pädagogen-Blog"

pt-br:
  url: "https://markleighedu.github.io"
  baseurl: "/pt-br"
  title: "Blog do Educador Mark Leigh"

tr:
  url: "https://markleighedu.github.io"
  baseurl: "/tr"
  title: "Mark Leigh Eğitimci Blogu"

ja:
  url: "https://markleighedu.github.io"
  baseurl: "/ja"
  title: "Mark Leighマーク・リー教育者ブログ"

ko:
  url: "https://markleighedu.github.io"
  baseurl: "/ko"
  title: "Mark Leigh 교육자 블로그"

defaults:
  - scope:
      path: "_posts"
    values:
      lang: en
  - scope:
      path: "es/_posts"
    values:
      lang: es
  - scope:
      path: "zh-cn/_posts"
    values:
      lang: zh-cn
  - scope:
      path: "zh-tw/_posts"
    values:
      lang: zh-tw
  - scope:
      path: "ar/_posts"
    values:
      lang: ar
  - scope:
      path: "fr/_posts"
    values:
      lang: fr
  - scope:
      path: "de/_posts"
    values:
      lang: de
  - scope:
      path: "pt-br/_posts"
    values:
      lang: pt-br
  - scope:
      path: "tr/_posts"
    values:
      lang: tr
  - scope:
      path: "ja/_posts"
    values:
      lang: ja
  - scope:
      path: "ko/_posts"
    values:
      lang: ko

# Site settings
SEOTitle: "Mark Leigh Blog | Trading Educator | Expert Financial Insights"
header-img: img/home-bg.jpg
email: markleigh.edu@gmail.com
description: "Mark Leigh's Personal Blog | Financial Market Trading Education"
keyword: "Mark Leigh, Educator, Education, Expert, Forex Trading, Currencies, Cryptocurrencies, Blog, Commodities Trading, US Stock Trading"
url: "https://markleighedu.github.io/"
baseurl: ""

# Publish posts or collection documents with a future date.
future: false

# SNS settings
RSS: false
instagram_username: markleigh.educator
tiktok_username: markleigh.edu
twitter_username: MarkLeigh_edu
youtube_username: "@MarkLeigh-Educator"
facebook_username: markleigh.tradingeducator
linkedin_username: mark-leigh-51132935

# Build settings
highlighter: rouge
permalink: pretty
paginate: 6
paginate_path: "/:lang/page:num/"
exclude:
  [
    "search.html",
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true
encoding: utf-8

# Plugins
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: markleigh
disable_disqus: true

# Analytics settings
ga_track_id: "G-XXXXXXXXXX"
ga_domain: markleighedu.github.io

# Sidebar settings
sidebar: true
sidebar-about-description: "Trading Education <br> Blog @ Mark"
sidebar-avatar: https://github.com/markleighedu.png

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page
page-mathjax: false
